### ISSUE TITLE
Extract palette colors as separate images

### ISSUE THREAD

**Issue by 8bitgentleman** [lobis/image-quantizer#1]
This is a very cool project, exactly what I was looking for. One request: Once the image has been converted to a specific palette, is there a way to export an image with each channel isolated separately? 

Some waveshare tri-color screens (looking at 7.5 white-black-red) need to be given 2 images. One to tell it where black goes and one to tell it where red goes. Could there be a way to extract the output of `image-quantizer` into those two images?

**Comment by lobis** [comment]
Hello @8bitgentleman ,

Thanks for taking an interest into this project and opening the first issue!

Since I only have the 7-color ePaper display I am not familiar with other displays but I would love for this repository to be compatible with more displays.

What you are asking is easily implemented, I will look into it this week.

On the meantime you can extract that information yourself since the result of `quantize_image` is a Pillow image object and I'm sure its straightforward to extract a single channel, see for instance https://stackoverflow.com/questions/17667780/use-python-imaging-library-to-isolate-a-single-channel.

Let me know if you need help with this.

**Comment by 8bitgentleman** [comment]
THANK YOU!! 
Had to modify your README example a little since `image.show()` was just a returned RGB Palettes not PIL images but otherwise seamless :))

```
from image_quantizer import quantize_image, split_image_by_color, PALETTES

with Image.open("tests/data/cliff.jpg") as image:
        quantized_image = quantize_image(image, palette=PALETTES["BLACK-WHITE-RED"])
        split_images = split_image_by_color(quantized_image)
        for color in split_images.keys():
            split_images[color].show()```
